try{
    hello();
}catch(error){
    console.log(error);
}


try {
    anotherFuncion();
}catch{
    console.log('esto es un error');
}